"""
Agent 5 - Markowitz Modern Portfolio Theory Optimizer
===============================================================================

PROJECT
-------
Agentic AI Portfolio Optimization and Algorithmic Trading

AGENT
-----
Agent 5 - Portfolio Rebalancing Agent

PURPOSE
-------
Determine the minimum-risk portfolio allocation using Markowitz
Modern Portfolio Theory after Agent-4 DQN trade execution.

PIPELINE
--------
Agent 4
BUY / SELL / HOLD
        ↓
Agent 5 return matrix
        ↓
Expected returns
        +
Covariance matrix
        ↓
Average target return
        ↓
Markowitz optimization
        ↓
Minimum-variance portfolio
        ↓
MPT weights
        ↓
rl_feedback.py
        ↓
Final rebalanced portfolio


REFERENCE-PAPER ALIGNMENT
-------------------------
The reference paper uses Markowitz MPT after DQN trade execution.

Core equations:

Portfolio expected return:

    Rp = Σ wi * Ri

Portfolio variance:

    σ²p = wᵀ Σ w

where:

    wi = asset weight
    Ri = expected asset return
    Σ  = covariance matrix

The paper states that target return is considered an average return
when determining the minimum-risk portfolio.


CURRENT IMPLEMENTATION
----------------------
Objective:

    minimize:

        wᵀ Σ w

Subject to:

    Σ wi = 1

    wᵀ μ = target return

    0 <= wi <= 1

Short selling is disabled.

Agent-4 SELL stocks are excluded from the optimization and receive
zero MPT weight.

BUY and HOLD stocks remain eligible.

IMPORTANT
---------
The paper does not provide the exact numerical optimizer or exact
software implementation.

This implementation uses scipy SLSQP because it supports:

    - equality constraints
    - bounds
    - nonlinear objective functions

This is a documented implementation reconstruction.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from scipy.optimize import minimize


# =============================================================================
# IMPORT PATH
# =============================================================================

AGENT_ROOT = (
    Path(__file__)
    .resolve()
    .parents[1]
)

if str(AGENT_ROOT) not in sys.path:

    sys.path.insert(
        0,
        str(
            AGENT_ROOT
        ),
    )


from config import config as cfg

from src.portfolio_metrics import (
    load_returns_matrix,
    load_rebalancing_input,
    portfolio_expected_return,
    portfolio_variance,
    portfolio_volatility,
    portfolio_sharpe_ratio,
    calculate_portfolio_metrics,
)


# =============================================================================
# BOOLEAN NORMALIZATION
# =============================================================================

def normalize_boolean_series(
    series: pd.Series,
) -> pd.Series:
    """
    Convert bool/string/integer representations into booleans.
    """

    if series.dtype == bool:

        return series.copy()

    return (
        series
        .astype(str)
        .str.strip()
        .str.lower()
        .isin(
            [
                "true",
                "1",
                "yes",
                "y",
            ]
        )
    )


# =============================================================================
# COVARIANCE MATRIX LOADER
# =============================================================================

def load_covariance_matrix() -> pd.DataFrame:
    """
    Load covariance matrix generated by data_loader.py.
    """

    if not cfg.COVARIANCE_MATRIX_CSV.exists():

        raise FileNotFoundError(
            "Covariance matrix was not found.\n"
            f"Expected:\n{cfg.COVARIANCE_MATRIX_CSV}\n\n"
            "Run Agent-5 data_loader.py first."
        )

    covariance = pd.read_csv(
        cfg.COVARIANCE_MATRIX_CSV,
        index_col=0,
    )

    covariance.index = (
        covariance.index
        .astype(str)
        .str.strip()
    )

    covariance.columns = (
        covariance.columns
        .astype(str)
        .str.strip()
    )

    covariance = covariance.apply(
        pd.to_numeric,
        errors="coerce",
    )

    if covariance.isna().any().any():

        raise ValueError(
            "Covariance matrix contains missing or "
            "non-numeric values."
        )

    covariance_values = covariance.to_numpy(
        dtype=float
    )

    if not np.isfinite(
        covariance_values
    ).all():

        raise ValueError(
            "Covariance matrix contains NaN or infinity."
        )

    if covariance.shape[0] != covariance.shape[1]:

        raise ValueError(
            "Covariance matrix is not square."
        )

    if not np.allclose(
        covariance_values,
        covariance_values.T,
        atol=1e-10,
    ):

        raise ValueError(
            "Covariance matrix is not symmetric."
        )

    return covariance


# =============================================================================
# OPTIMIZER INPUT PREPARATION
# =============================================================================

def prepare_optimizer_inputs() -> dict[str, Any]:
    """
    Load and align all MPT inputs.

    Returns:
        returns
        eligible_returns
        rebalancing_input
        eligible_rows
        eligible_symbols
        expected_returns
        covariance
        target_return
    """

    returns = load_returns_matrix()

    rebalancing_input = (
        load_rebalancing_input()
    )

    rebalancing_input = (
        rebalancing_input
        .copy()
    )

    rebalancing_input[
        "symbol"
    ] = (
        rebalancing_input[
            "symbol"
        ]
        .astype(str)
        .str.strip()
    )

    rebalancing_input[
        "trade_action"
    ] = (
        rebalancing_input[
            "trade_action"
        ]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    rebalancing_input[
        "eligible_for_mpt"
    ] = normalize_boolean_series(
        rebalancing_input[
            "eligible_for_mpt"
        ]
    )

    # -------------------------------------------------------------------------
    # VALIDATE ACTIONS
    # -------------------------------------------------------------------------

    if not rebalancing_input[
        "trade_action"
    ].isin(
        cfg.VALID_ACTIONS
    ).all():

        invalid = (
            rebalancing_input.loc[
                ~rebalancing_input[
                    "trade_action"
                ].isin(
                    cfg.VALID_ACTIONS
                ),
                "trade_action",
            ]
            .unique()
            .tolist()
        )

        raise ValueError(
            "Invalid trade actions found:\n"
            f"{invalid}"
        )

    # -------------------------------------------------------------------------
    # MPT-ELIGIBLE ASSETS
    # -------------------------------------------------------------------------

    eligible_rows = (
        rebalancing_input.loc[
            rebalancing_input[
                "eligible_for_mpt"
            ]
        ]
        .copy()
        .reset_index(
            drop=True
        )
    )

    if eligible_rows.empty:

        raise ValueError(
            "No MPT-eligible assets are available."
        )

    eligible_symbols = (
        eligible_rows[
            "symbol"
        ]
        .tolist()
    )

    # -------------------------------------------------------------------------
    # VERIFY BUY/HOLD ELIGIBILITY
    # -------------------------------------------------------------------------

    if not eligible_rows[
        "trade_action"
    ].isin(
        cfg.MPT_ELIGIBLE_ACTIONS
    ).all():

        raise ValueError(
            "An MPT-eligible stock has an invalid "
            "Agent-4 action."
        )

    # -------------------------------------------------------------------------
    # VERIFY SELL EXCLUSION
    # -------------------------------------------------------------------------

    sell_rows = (
        rebalancing_input[
            "trade_action"
        ]
        ==
        cfg.ACTION_SELL
    )

    if sell_rows.any():

        if rebalancing_input.loc[
            sell_rows,
            "eligible_for_mpt",
        ].any():

            raise ValueError(
                "A SELL stock is incorrectly eligible "
                "for MPT optimization."
            )

    # -------------------------------------------------------------------------
    # RETURN MATRIX ALIGNMENT
    # -------------------------------------------------------------------------

    missing_return_symbols = [
        symbol
        for symbol in eligible_symbols
        if symbol not in returns.columns
    ]

    if missing_return_symbols:

        raise ValueError(
            "MPT assets missing from returns matrix:\n"
            +
            "\n".join(
                missing_return_symbols
            )
        )

    eligible_returns = (
        returns[
            eligible_symbols
        ]
        .copy()
    )

    if eligible_returns.empty:

        raise ValueError(
            "Eligible return matrix is empty."
        )

    if not np.isfinite(
        eligible_returns.to_numpy(
            dtype=float
        )
    ).all():

        raise ValueError(
            "Eligible return matrix contains "
            "invalid numerical values."
        )

    # -------------------------------------------------------------------------
    # EXPECTED RETURNS
    # -------------------------------------------------------------------------
    #
    # Markowitz mean-return input.
    #
    # Arithmetic annualization is used here because:
    #
    #     E[Rannual] ≈ E[Rdaily] × 252
    #
    # and covariance is also annualized by ×252.
    # -------------------------------------------------------------------------

    expected_returns = (
        eligible_returns.mean()
        *
        cfg.TRADING_DAYS_PER_YEAR
    )

    expected_returns = expected_returns.reindex(
        eligible_symbols
    )

    if expected_returns.isna().any():

        raise ValueError(
            "Expected return vector contains missing values."
        )

    # -------------------------------------------------------------------------
    # COVARIANCE
    # -------------------------------------------------------------------------

    covariance = load_covariance_matrix()

    missing_covariance_symbols = [
        symbol
        for symbol in eligible_symbols
        if (
            symbol not in covariance.columns
            or
            symbol not in covariance.index
        )
    ]

    if missing_covariance_symbols:

        raise ValueError(
            "Eligible assets missing from covariance matrix:\n"
            +
            "\n".join(
                missing_covariance_symbols
            )
        )

    covariance = covariance.loc[
        eligible_symbols,
        eligible_symbols,
    ]

    # -------------------------------------------------------------------------
    # TARGET RETURN
    # -------------------------------------------------------------------------
    #
    # Paper-aligned interpretation:
    #
    # target return = average return of eligible assets.
    #
    # Since an equal-weight portfolio gives the arithmetic average
    # of individual expected returns, it is automatically feasible.
    # -------------------------------------------------------------------------

    target_return = float(
        expected_returns.mean()
    )

    return {
        "returns":
            returns,

        "eligible_returns":
            eligible_returns,

        "rebalancing_input":
            rebalancing_input,

        "eligible_rows":
            eligible_rows,

        "eligible_symbols":
            eligible_symbols,

        "expected_returns":
            expected_returns,

        "covariance":
            covariance,

        "target_return":
            target_return,
    }


# =============================================================================
# RAW OBJECTIVE
# =============================================================================

def variance_objective(
    weights: np.ndarray,
    covariance_matrix: np.ndarray,
) -> float:
    """
    Markowitz minimum-variance objective.

        objective = w.T @ covariance @ w

    This function intentionally performs no weight-sum validation because
    SLSQP evaluates trial points that may temporarily violate constraints.
    """

    weights = np.asarray(
        weights,
        dtype=float,
    )

    covariance_matrix = np.asarray(
        covariance_matrix,
        dtype=float,
    )

    value = float(
        weights.T
        @
        covariance_matrix
        @
        weights
    )

    return value


# =============================================================================
# WEIGHT-SUM CONSTRAINT
# =============================================================================

def weight_sum_constraint(
    weights: np.ndarray,
) -> float:
    """
    Equality constraint:

        sum(weights) = 1
    """

    return float(
        np.sum(
            weights
        )
        -
        cfg.WEIGHT_SUM_TARGET
    )


# =============================================================================
# TARGET-RETURN CONSTRAINT
# =============================================================================

def target_return_constraint(
    weights: np.ndarray,
    expected_returns: np.ndarray,
    target_return: float,
) -> float:
    """
    Equality constraint:

        w.T @ expected_returns = target_return
    """

    return float(
        np.dot(
            weights,
            expected_returns,
        )
        -
        target_return
    )


# =============================================================================
# MARKOWITZ OPTIMIZATION
# =============================================================================

def optimize_minimum_variance(
    expected_returns: pd.Series,
    covariance: pd.DataFrame,
    target_return: float,
) -> dict[str, Any]:
    """
    Solve the constrained Markowitz optimization.

    Minimize:

        w.T Σ w

    Subject to:

        Σ w = 1

        w.T μ = target return

        MIN_WEIGHT <= wi <= MAX_WEIGHT
    """

    symbols = (
        expected_returns.index
        .astype(str)
        .tolist()
    )

    number_of_assets = len(
        symbols
    )

    if number_of_assets < 1:

        raise ValueError(
            "No assets supplied to MPT optimizer."
        )

    covariance = covariance.loc[
        symbols,
        symbols,
    ]

    expected_return_vector = (
        expected_returns
        .to_numpy(
            dtype=float
        )
    )

    covariance_matrix = (
        covariance
        .to_numpy(
            dtype=float
        )
    )

    if not np.isfinite(
        expected_return_vector
    ).all():

        raise ValueError(
            "Expected returns contain invalid values."
        )

    if not np.isfinite(
        covariance_matrix
    ).all():

        raise ValueError(
            "Covariance contains invalid values."
        )

    # -------------------------------------------------------------------------
    # EQUAL-WEIGHT STARTING POINT
    # -------------------------------------------------------------------------
    #
    # Because target return is the mean asset return, equal weights
    # satisfy both equality constraints by construction.
    # -------------------------------------------------------------------------

    initial_weights = np.full(
        number_of_assets,
        1.0
        /
        number_of_assets,
        dtype=float,
    )

    initial_expected_return = float(
        np.dot(
            initial_weights,
            expected_return_vector,
        )
    )

    initial_variance = variance_objective(
        weights=initial_weights,
        covariance_matrix=covariance_matrix,
    )

    # -------------------------------------------------------------------------
    # BOUNDS
    # -------------------------------------------------------------------------

    bounds = [
        (
            cfg.MIN_WEIGHT,
            cfg.MAX_WEIGHT,
        )
        for _ in range(
            number_of_assets
        )
    ]

    # -------------------------------------------------------------------------
    # CONSTRAINTS
    # -------------------------------------------------------------------------

    constraints = [
        {
            "type":
                "eq",

            "fun":
                weight_sum_constraint,
        },

        {
            "type":
                "eq",

            "fun":
                lambda weights: target_return_constraint(
                    weights=weights,
                    expected_returns=expected_return_vector,
                    target_return=target_return,
                ),
        },
    ]

    # -------------------------------------------------------------------------
    # OPTIMIZE
    # -------------------------------------------------------------------------

    result = minimize(
        fun=variance_objective,

        x0=initial_weights,

        args=(
            covariance_matrix,
        ),

        method=cfg.OPTIMIZER_METHOD,

        bounds=bounds,

        constraints=constraints,

        options={
            "maxiter":
                cfg.OPTIMIZER_MAX_ITERATIONS,

            "ftol":
                cfg.OPTIMIZER_FTOL,

            "disp":
                False,
        },
    )

    if not result.success:

        raise RuntimeError(
            "Markowitz optimization failed.\n"
            f"Status : {result.status}\n"
            f"Message: {result.message}"
        )

    optimized_weights = np.asarray(
        result.x,
        dtype=float,
    )

    # Small floating-point values near zero.
    optimized_weights[
        np.abs(
            optimized_weights
        )
        <
        1e-12
    ] = 0.0

    weight_sum = float(
        optimized_weights.sum()
    )

    optimized_expected_return = float(
        np.dot(
            optimized_weights,
            expected_return_vector,
        )
    )

    optimized_variance = variance_objective(
        weights=optimized_weights,
        covariance_matrix=covariance_matrix,
    )

    optimized_volatility = float(
        np.sqrt(
            max(
                optimized_variance,
                0.0,
            )
        )
    )

    # -------------------------------------------------------------------------
    # FINAL CONSTRAINT VALIDATION
    # -------------------------------------------------------------------------

    checks = {
        "optimizer_success":
            bool(
                result.success
            ),

        "weights_finite":
            bool(
                np.isfinite(
                    optimized_weights
                ).all()
            ),

        "weights_nonnegative":
            bool(
                (
                    optimized_weights
                    >=
                    (
                        cfg.MIN_WEIGHT
                        -
                        cfg.FLOAT_TOLERANCE
                    )
                )
                .all()
            ),

        "weights_below_max":
            bool(
                (
                    optimized_weights
                    <=
                    (
                        cfg.MAX_WEIGHT
                        +
                        cfg.FLOAT_TOLERANCE
                    )
                )
                .all()
            ),

        "weights_sum_to_one":
            bool(
                np.isclose(
                    weight_sum,
                    cfg.WEIGHT_SUM_TARGET,
                    atol=cfg.WEIGHT_SUM_TOLERANCE,
                )
            ),

        "target_return_satisfied":
            bool(
                np.isclose(
                    optimized_expected_return,
                    target_return,
                    atol=cfg.TARGET_RETURN_TOLERANCE,
                )
            ),

        "variance_finite":
            bool(
                np.isfinite(
                    optimized_variance
                )
            ),

        "variance_nonnegative":
            bool(
                optimized_variance
                >=
                -cfg.FLOAT_TOLERANCE
            ),

        "variance_not_above_equal_weight":
            bool(
                optimized_variance
                <=
                (
                    initial_variance
                    +
                    1e-8
                )
            ),
    }

    if not all(
        checks.values()
    ):

        failed = [
            name
            for name, passed
            in checks.items()
            if not passed
        ]

        raise ValueError(
            "Optimized portfolio failed validation:\n"
            +
            "\n".join(
                f"  - {name}"
                for name
                in failed
            )
        )

    return {
        "symbols":
            symbols,

        "weights":
            optimized_weights,

        "initial_weights":
            initial_weights,

        "initial_return":
            initial_expected_return,

        "initial_variance":
            initial_variance,

        "target_return":
            target_return,

        "expected_return":
            optimized_expected_return,

        "variance":
            optimized_variance,

        "volatility":
            optimized_volatility,

        "optimizer_result":
            result,

        "checks":
            checks,
    }


# =============================================================================
# CREATE COMPLETE MPT SOLUTION TABLE
# =============================================================================

def build_mpt_solution(
    rebalancing_input: pd.DataFrame,
    returns: pd.DataFrame,
    eligible_symbols: list[str],
    optimized_weights: np.ndarray,
) -> pd.DataFrame:
    """
    Create a complete solution containing all ten Agent-4 stocks.

    Eligible BUY/HOLD stocks receive optimized MPT weights.

    SELL stocks receive exactly zero MPT weight.
    """

    solution = (
        rebalancing_input
        .copy()
    )

    solution[
        "symbol"
    ] = (
        solution[
            "symbol"
        ]
        .astype(str)
        .str.strip()
    )

    # -------------------------------------------------------------------------
    # EXPECTED RETURN FOR ALL STOCKS
    # -------------------------------------------------------------------------

    all_expected_returns = (
        returns.mean()
        *
        cfg.TRADING_DAYS_PER_YEAR
    )

    solution[
        "mpt_expected_return"
    ] = (
        solution[
            "symbol"
        ]
        .map(
            all_expected_returns
            .to_dict()
        )
    )

    # -------------------------------------------------------------------------
    # WEIGHT MAP
    # -------------------------------------------------------------------------

    weight_map = {
        symbol:
            float(
                weight
            )

        for symbol, weight
        in zip(
            eligible_symbols,
            optimized_weights,
        )
    }

    solution[
        "mpt_weight"
    ] = (
        solution[
            "symbol"
        ]
        .map(
            weight_map
        )
        .fillna(
            cfg.SELL_TARGET_WEIGHT
        )
        .astype(float)
    )

    solution[
        "mpt_allocation_percent"
    ] = (
        solution[
            "mpt_weight"
        ]
        *
        100.0
    )

    solution[
        "sell_zero_weight_enforced"
    ] = (
        solution[
            "trade_action"
        ]
        .astype(str)
        .str.upper()
        .eq(
            cfg.ACTION_SELL
        )
    )

    # -------------------------------------------------------------------------
    # RANK BY ALLOCATION
    # -------------------------------------------------------------------------

    solution[
        "mpt_allocation_rank"
    ] = (
        solution[
            "mpt_weight"
        ]
        .rank(
            method="dense",
            ascending=False,
        )
        .astype(int)
    )

    # -------------------------------------------------------------------------
    # SORT
    # -------------------------------------------------------------------------

    solution = (
        solution
        .sort_values(
            [
                "mpt_weight",
                "symbol",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )

    return solution


# =============================================================================
# FINAL SOLUTION VALIDATION
# =============================================================================

def validate_solution_table(
    solution: pd.DataFrame,
    eligible_symbols: list[str],
) -> dict[str, bool]:
    """
    Validate all-stock Agent-5 MPT solution.
    """

    weights = (
        solution[
            "mpt_weight"
        ]
        .to_numpy(
            dtype=float
        )
    )

    sell_rows = (
        solution[
            "trade_action"
        ]
        .astype(str)
        .str.upper()
        .eq(
            cfg.ACTION_SELL
        )
    )

    eligible_rows = (
        solution[
            "symbol"
        ]
        .isin(
            eligible_symbols
        )
    )

    checks = {
        "solution_not_empty":
            not solution.empty,

        "one_row_per_symbol":
            not solution[
                "symbol"
            ]
            .duplicated()
            .any(),

        "weights_finite":
            bool(
                np.isfinite(
                    weights
                ).all()
            ),

        "weights_nonnegative":
            bool(
                (
                    weights
                    >=
                    (
                        cfg.MIN_WEIGHT
                        -
                        cfg.FLOAT_TOLERANCE
                    )
                )
                .all()
            ),

        "weights_sum_to_one":
            bool(
                np.isclose(
                    weights.sum(),
                    cfg.WEIGHT_SUM_TARGET,
                    atol=cfg.WEIGHT_SUM_TOLERANCE,
                )
            ),

        "sell_weights_zero":
            bool(
                np.allclose(
                    solution.loc[
                        sell_rows,
                        "mpt_weight",
                    ]
                    .to_numpy(
                        dtype=float
                    ),
                    cfg.SELL_TARGET_WEIGHT,
                    atol=cfg.FLOAT_TOLERANCE,
                )
            ),

        "eligible_assets_match":
            set(
                solution.loc[
                    eligible_rows,
                    "symbol",
                ]
            )
            ==
            set(
                eligible_symbols
            ),

        "all_positive_weights_belong_to_eligible_assets":
            bool(
                solution.loc[
                    solution[
                        "mpt_weight"
                    ]
                    >
                    cfg.FLOAT_TOLERANCE,
                    "symbol",
                ]
                .isin(
                    eligible_symbols
                )
                .all()
            ),
    }

    return checks


# =============================================================================
# COMPLETE MPT OPTIMIZER
# =============================================================================

def run_mpt_optimization() -> dict[str, Any]:
    """
    Execute complete Markowitz optimization.
    """

    print()
    print(
        "=" * 100
    )

    print(
        "AGENT 5 - MARKOWITZ MPT OPTIMIZER"
    )

    print(
        "=" * 100
    )

    print()

    # =========================================================================
    # LOAD INPUTS
    # =========================================================================

    inputs = (
        prepare_optimizer_inputs()
    )

    returns = (
        inputs[
            "returns"
        ]
    )

    eligible_returns = (
        inputs[
            "eligible_returns"
        ]
    )

    rebalancing_input = (
        inputs[
            "rebalancing_input"
        ]
    )

    eligible_symbols = (
        inputs[
            "eligible_symbols"
        ]
    )

    expected_returns = (
        inputs[
            "expected_returns"
        ]
    )

    covariance = (
        inputs[
            "covariance"
        ]
    )

    target_return = (
        inputs[
            "target_return"
        ]
    )

    number_of_assets = len(
        eligible_symbols
    )

    print(
        f"Eligible assets         : "
        f"{number_of_assets}"
    )

    print(
        f"Return observations     : "
        f"{len(eligible_returns)}"
    )

    print(
        f"Target return           : "
        f"{target_return:.6%}"
    )

    print()

    print(
        "EXPECTED RETURNS"
    )

    print(
        "-" * 100
    )

    for symbol in eligible_symbols:

        print(
            f"{symbol:<20} "
            f"{expected_returns.loc[symbol]:>12.6%}"
        )

    # =========================================================================
    # OPTIMIZE
    # =========================================================================

    optimization = (
        optimize_minimum_variance(
            expected_returns=expected_returns,
            covariance=covariance,
            target_return=target_return,
        )
    )

    optimized_weights = (
        optimization[
            "weights"
        ]
    )

    equal_weights = (
        optimization[
            "initial_weights"
        ]
    )

    # =========================================================================
    # EXPECTED EQUAL-WEIGHT METRICS
    # =========================================================================

    equal_expected_return = (
        portfolio_expected_return(
            weights=equal_weights,
            expected_returns=expected_returns.to_numpy(
                dtype=float
            ),
        )
    )

    equal_variance = (
        portfolio_variance(
            weights=equal_weights,
            covariance_matrix=covariance.to_numpy(
                dtype=float
            ),
        )
    )

    equal_volatility = (
        portfolio_volatility(
            weights=equal_weights,
            covariance_matrix=covariance.to_numpy(
                dtype=float
            ),
        )
    )

    equal_sharpe = (
        portfolio_sharpe_ratio(
            portfolio_return=equal_expected_return,
            portfolio_volatility_value=equal_volatility,
        )
    )

    # =========================================================================
    # EXPECTED OPTIMIZED METRICS
    # =========================================================================

    optimized_expected_return = (
        portfolio_expected_return(
            weights=optimized_weights,
            expected_returns=expected_returns.to_numpy(
                dtype=float
            ),
        )
    )

    optimized_variance = (
        portfolio_variance(
            weights=optimized_weights,
            covariance_matrix=covariance.to_numpy(
                dtype=float
            ),
        )
    )

    optimized_volatility = (
        portfolio_volatility(
            weights=optimized_weights,
            covariance_matrix=covariance.to_numpy(
                dtype=float
            ),
        )
    )

    optimized_sharpe = (
        portfolio_sharpe_ratio(
            portfolio_return=optimized_expected_return,
            portfolio_volatility_value=optimized_volatility,
        )
    )

    # =========================================================================
    # HISTORICAL ESTIMATION-WINDOW METRICS
    # =========================================================================
    #
    # IMPORTANT:
    #
    # These describe the same 105-day historical window used to estimate
    # MPT inputs.
    #
    # They are NOT a post-2025-12-01 future backtest.
    # =========================================================================

    equal_historical_metrics = (
        calculate_portfolio_metrics(
            returns=eligible_returns,
            weights=equal_weights,
        )
    )

    optimized_historical_metrics = (
        calculate_portfolio_metrics(
            returns=eligible_returns,
            weights=optimized_weights,
            previous_weights=equal_weights,
        )
    )

    # =========================================================================
    # VARIANCE REDUCTION
    # =========================================================================

    if equal_variance > 0:

        variance_reduction = (
            (
                equal_variance
                -
                optimized_variance
            )
            /
            equal_variance
        )

    else:

        variance_reduction = 0.0

    if equal_volatility > 0:

        volatility_reduction = (
            (
                equal_volatility
                -
                optimized_volatility
            )
            /
            equal_volatility
        )

    else:

        volatility_reduction = 0.0

    # =========================================================================
    # DISPLAY OPTIMIZED WEIGHTS
    # =========================================================================

    print()
    print(
        "=" * 100
    )

    print(
        "MPT OPTIMIZED PORTFOLIO"
    )

    print(
        "=" * 100
    )

    print()

    for symbol, weight in zip(
        eligible_symbols,
        optimized_weights,
    ):

        print(
            f"{symbol:<20} "
            f"{weight:>12.6%}"
        )

    print()
    print(
        "Expected return         : "
        f"{optimized_expected_return:.6%}"
    )

    print(
        "Target return           : "
        f"{target_return:.6%}"
    )

    print(
        "Portfolio variance      : "
        f"{optimized_variance:.8f}"
    )

    print(
        "Portfolio volatility    : "
        f"{optimized_volatility:.6%}"
    )

    print(
        "Expected Sharpe ratio   : "
        f"{optimized_sharpe:.6f}"
    )

    print()

    print(
        "Variance reduction      : "
        f"{variance_reduction:.6%}"
    )

    print(
        "Volatility reduction    : "
        f"{volatility_reduction:.6%}"
    )

    # =========================================================================
    # SOLUTION TABLE
    # =========================================================================

    solution = build_mpt_solution(
        rebalancing_input=rebalancing_input,
        returns=returns,
        eligible_symbols=eligible_symbols,
        optimized_weights=optimized_weights,
    )

    solution_checks = (
        validate_solution_table(
            solution=solution,
            eligible_symbols=eligible_symbols,
        )
    )

    optimizer_checks = (
        optimization[
            "checks"
        ]
    )

    all_checks = {
        **{
            f"optimizer_{name}":
                bool(
                    value
                )

            for name, value
            in optimizer_checks.items()
        },

        **{
            f"solution_{name}":
                bool(
                    value
                )

            for name, value
            in solution_checks.items()
        },
    }

    overall_pass = all(
        all_checks.values()
    )

    # =========================================================================
    # VALIDATION DISPLAY
    # =========================================================================

    print()
    print(
        "=" * 100
    )

    print(
        "MPT OPTIMIZER VALIDATION"
    )

    print(
        "=" * 100
    )

    print()

    for name, passed in all_checks.items():

        print(
            f"{name:<65}: "
            f"{passed}"
        )

    print()

    print(
        "VALIDATION RESULT: "
        f"{'PASS' if overall_pass else 'FAIL'}"
    )

    if not overall_pass:

        failed = [
            name
            for name, passed
            in all_checks.items()
            if not passed
        ]

        raise ValueError(
            "MPT optimizer validation failed:\n"
            +
            "\n".join(
                f"  - {name}"
                for name
                in failed
            )
        )

    # =========================================================================
    # SAVE SOLUTION
    # =========================================================================

    cfg.MPT_SOLUTION_CSV.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    solution.to_csv(
        cfg.MPT_SOLUTION_CSV,
        index=False,
    )

    # =========================================================================
    # SERIALIZABLE WEIGHT DICTIONARY
    # =========================================================================

    optimized_weight_dict = {
        symbol:
            float(
                weight
            )

        for symbol, weight
        in zip(
            eligible_symbols,
            optimized_weights,
        )
    }

    equal_weight_dict = {
        symbol:
            float(
                weight
            )

        for symbol, weight
        in zip(
            eligible_symbols,
            equal_weights,
        )
    }

    # =========================================================================
    # REPORT
    # =========================================================================

    report = {
        "status":
            "COMPLETE",

        "method":
            "Markowitz minimum-variance optimization",

        "optimizer":
            cfg.OPTIMIZER_METHOD,

        "objective":
            cfg.MPT_OBJECTIVE,

        "target_return_mode":
            cfg.TARGET_RETURN_MODE,

        "rebalance_date":
            cfg.FINAL_REBALANCE_DATE,

        "eligible_assets":
            int(
                number_of_assets
            ),

        "eligible_symbols":
            eligible_symbols,

        "return_observations":
            int(
                len(
                    eligible_returns
                )
            ),

        "target_return":
            float(
                target_return
            ),

        "expected_asset_returns": {
            symbol:
                float(
                    expected_returns.loc[
                        symbol
                    ]
                )

            for symbol
            in eligible_symbols
        },

        "equal_weight_portfolio": {
            "weights":
                equal_weight_dict,

            "expected_return":
                float(
                    equal_expected_return
                ),

            "variance":
                float(
                    equal_variance
                ),

            "volatility":
                float(
                    equal_volatility
                ),

            "sharpe_ratio":
                float(
                    equal_sharpe
                ),

            "historical_estimation_window_metrics":
                {
                    key:
                        (
                            int(value)
                            if isinstance(
                                value,
                                (
                                    int,
                                    np.integer,
                                ),
                            )
                            else
                            float(value)
                        )

                    for key, value
                    in equal_historical_metrics.items()
                },
        },

        "optimized_portfolio": {
            "weights":
                optimized_weight_dict,

            "expected_return":
                float(
                    optimized_expected_return
                ),

            "variance":
                float(
                    optimized_variance
                ),

            "volatility":
                float(
                    optimized_volatility
                ),

            "sharpe_ratio":
                float(
                    optimized_sharpe
                ),

            "variance_reduction_vs_equal_weight":
                float(
                    variance_reduction
                ),

            "volatility_reduction_vs_equal_weight":
                float(
                    volatility_reduction
                ),

            "historical_estimation_window_metrics":
                {
                    key:
                        (
                            int(value)
                            if isinstance(
                                value,
                                (
                                    int,
                                    np.integer,
                                ),
                            )
                            else
                            float(value)
                        )

                    for key, value
                    in optimized_historical_metrics.items()
                },
        },

        "constraints": {
            "weight_sum":
                cfg.WEIGHT_SUM_TARGET,

            "minimum_weight":
                cfg.MIN_WEIGHT,

            "maximum_weight":
                cfg.MAX_WEIGHT,

            "short_selling":
                cfg.ALLOW_SHORT_SELLING,

            "sell_target_weight":
                cfg.SELL_TARGET_WEIGHT,

            "target_return_equality":
                True,
        },

        "solver": {
            "success":
                bool(
                    optimization[
                        "optimizer_result"
                    ].success
                ),

            "status":
                int(
                    optimization[
                        "optimizer_result"
                    ].status
                ),

            "message":
                str(
                    optimization[
                        "optimizer_result"
                    ].message
                ),

            "iterations":
                int(
                    getattr(
                        optimization[
                            "optimizer_result"
                        ],
                        "nit",
                        0,
                    )
                ),

            "function_evaluations":
                int(
                    getattr(
                        optimization[
                            "optimizer_result"
                        ],
                        "nfev",
                        0,
                    )
                ),
        },

        "validation": {
            name:
                bool(
                    value
                )

            for name, value
            in all_checks.items()
        },

        "output":
            str(
                cfg.MPT_SOLUTION_CSV
            ),

        "methodology_note":
            (
                "The reference paper specifies Markowitz MPT using "
                "mean return, covariance and minimum-risk portfolio "
                "construction with average target return. The exact "
                "numerical solver and DQN-action-to-weight mapping are "
                "not completely specified. This implementation uses "
                "SLSQP, excludes Agent-4 SELL stocks by assigning zero "
                "allocation, and optimizes BUY/HOLD assets under a "
                "fully invested long-only portfolio constraint."
            ),

        "evaluation_note":
            (
                "Historical metrics in this report use the same "
                "105-day estimation window used to construct MPT "
                "inputs. They must not be interpreted as a future "
                "post-rebalance backtest."
            ),
    }

    cfg.REPORT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        cfg.MPT_OPTIMIZATION_SUMMARY,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            report,
            file,
            indent=4,
        )

    # =========================================================================
    # FINAL DISPLAY
    # =========================================================================

    print()
    print(
        "=" * 100
    )

    print(
        "GENERATED FILES"
    )

    print(
        "=" * 100
    )

    print()

    print(
        f"MPT solution            : "
        f"{cfg.MPT_SOLUTION_CSV}"
    )

    print(
        f"Optimization summary    : "
        f"{cfg.MPT_OPTIMIZATION_SUMMARY}"
    )

    print()

    print(
        "=" * 100
    )

    print(
        "MPT OPTIMIZER STATUS"
    )

    print(
        "=" * 100
    )

    print()

    print(
        "Expected returns         : COMPLETE"
    )

    print(
        "Covariance matrix        : COMPLETE"
    )

    print(
        "Average target return    : COMPLETE"
    )

    print(
        "Minimum variance         : COMPLETE"
    )

    print(
        "Weight constraints       : COMPLETE"
    )

    print(
        "SELL zero allocation     : COMPLETE"
    )

    print(
        "Optimizer validation     : COMPLETE"
    )

    print(
        "Solution persistence     : COMPLETE"
    )

    print()

    print(
        "MPT OPTIMIZER STATUS: COMPLETE"
    )

    return {
        "inputs":
            inputs,

        "optimization":
            optimization,

        "solution":
            solution,

        "equal_weight_metrics":
            equal_historical_metrics,

        "optimized_metrics":
            optimized_historical_metrics,

        "checks":
            all_checks,

        "report":
            report,
    }


# =============================================================================
# DIRECT EXECUTION
# =============================================================================

if __name__ == "__main__":

    run_mpt_optimization()