"""
Agent 5 - RL Feedback Layer
===============================================================================

PROJECT
-------
Agentic AI Portfolio Optimization and Algorithmic Trading

AGENT
-----
Agent 5 - Portfolio Rebalancing Agent

PURPOSE
-------
Combine:

    Agent-4 DQN trade decisions

with:

    Agent-5 Markowitz MPT optimized weights

to produce the RL-aware portfolio allocation used by the final
rebalancing agent.


PIPELINE
--------
Agent 4 DQN
BUY / SELL / HOLD
        |
        v
Agent 5 MPT
minimum-variance weights
        |
        v
RL Feedback Layer
        |
        +---- SELL -> force weight = 0
        |
        +---- BUY  -> preserve MPT allocation
        |
        +---- HOLD -> preserve MPT allocation
        |
        v
Normalize remaining allocation
        |
        v
RL-adjusted portfolio weights


REFERENCE-PAPER INTERPRETATION
------------------------------
The reference paper combines Markowitz MPT with reinforcement learning
for portfolio rebalancing.

The paper does not provide a complete software-level equation that maps
DQN BUY / SELL / HOLD actions into numerical portfolio weights.

Therefore this implementation uses a transparent reconstruction:

    SELL -> zero allocation

    BUY  -> MPT determines allocation

    HOLD -> MPT determines allocation

No arbitrary BUY multiplier is introduced.

No arbitrary HOLD multiplier is introduced.

This avoids inventing parameters that are not reported in the paper.


IMPORTANT
---------
Agent 4 is already the learned DQN reinforcement-learning component.

This module does NOT train another neural network.

Instead, it transfers the DQN action into the portfolio-rebalancing
decision layer.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd


# =============================================================================
# IMPORT PATH
# =============================================================================

AGENT_ROOT = (
    Path(__file__)
    .resolve()
    .parents[1]
)

if str(AGENT_ROOT) not in sys.path:

    sys.path.insert(
        0,
        str(
            AGENT_ROOT
        ),
    )


from config import config as cfg


# =============================================================================
# LOAD MPT SOLUTION
# =============================================================================

def load_mpt_solution() -> pd.DataFrame:
    """
    Load mpt_solution.csv generated by mpt_optimizer.py.
    """

    if not cfg.MPT_SOLUTION_CSV.exists():

        raise FileNotFoundError(
            "MPT solution was not found.\n\n"
            f"Expected:\n"
            f"{cfg.MPT_SOLUTION_CSV}\n\n"
            "Run mpt_optimizer.py first."
        )

    dataframe = pd.read_csv(
        cfg.MPT_SOLUTION_CSV,
        low_memory=False,
    )

    if dataframe.empty:

        raise ValueError(
            "MPT solution is empty."
        )

    required_columns = {
        "symbol",
        "trade_action",
        "mpt_weight",
    }

    missing_columns = (
        required_columns
        -
        set(
            dataframe.columns
        )
    )

    if missing_columns:

        raise ValueError(
            "MPT solution is missing required columns:\n"
            +
            "\n".join(
                sorted(
                    missing_columns
                )
            )
        )

    dataframe = dataframe.copy()

    dataframe[
        "symbol"
    ] = (
        dataframe[
            "symbol"
        ]
        .astype(str)
        .str.strip()
    )

    dataframe[
        "trade_action"
    ] = (
        dataframe[
            "trade_action"
        ]
        .astype(str)
        .str.upper()
        .str.strip()
    )

    dataframe[
        "mpt_weight"
    ] = pd.to_numeric(
        dataframe[
            "mpt_weight"
        ],
        errors="coerce",
    )

    if dataframe[
        "symbol"
    ].duplicated().any():

        duplicated = (
            dataframe.loc[
                dataframe[
                    "symbol"
                ].duplicated(
                    keep=False
                ),
                "symbol",
            ]
            .tolist()
        )

        raise ValueError(
            "Duplicate symbols in MPT solution:\n"
            +
            "\n".join(
                sorted(
                    set(
                        duplicated
                    )
                )
            )
        )

    if dataframe[
        "mpt_weight"
    ].isna().any():

        raise ValueError(
            "MPT solution contains invalid weights."
        )

    if not np.isfinite(
        dataframe[
            "mpt_weight"
        ]
        .to_numpy(
            dtype=float
        )
    ).all():

        raise ValueError(
            "MPT weights contain NaN or infinity."
        )

    if not dataframe[
        "trade_action"
    ].isin(
        cfg.VALID_ACTIONS
    ).all():

        invalid_actions = (
            dataframe.loc[
                ~dataframe[
                    "trade_action"
                ].isin(
                    cfg.VALID_ACTIONS
                ),
                "trade_action",
            ]
            .unique()
            .tolist()
        )

        raise ValueError(
            "Invalid Agent-4 actions in MPT solution:\n"
            f"{invalid_actions}"
        )

    return dataframe


# =============================================================================
# VERIFY MPT OPTIMIZATION REPORT
# =============================================================================

def load_mpt_report() -> dict[str, Any]:
    """
    Verify that MPT optimization completed successfully.
    """

    if not cfg.MPT_OPTIMIZATION_SUMMARY.exists():

        raise FileNotFoundError(
            "MPT optimization summary was not found.\n"
            f"Expected:\n"
            f"{cfg.MPT_OPTIMIZATION_SUMMARY}"
        )

    with open(
        cfg.MPT_OPTIMIZATION_SUMMARY,
        "r",
        encoding="utf-8",
    ) as file:

        report = json.load(
            file
        )

    if (
        str(
            report.get(
                "status",
                "",
            )
        )
        .upper()
        !=
        "COMPLETE"
    ):

        raise ValueError(
            "MPT optimization report does not have "
            "status COMPLETE."
        )

    return report


# =============================================================================
# ACTION Q-VALUE MARGIN
# =============================================================================

def calculate_q_margin(
    dataframe: pd.DataFrame,
) -> pd.Series:
    """
    Calculate the difference between:

        selected Q-value

    and:

        second-highest Q-value

    This provides a diagnostic measure of DQN action separation.

    IMPORTANT:
    Q-margin is NOT used to modify portfolio weights.

    It is included only for interpretability.
    """

    q_columns = [
        "q_hold",
        "q_buy",
        "q_sell",
    ]

    if not all(
        column in dataframe.columns
        for column in q_columns
    ):

        return pd.Series(
            np.nan,
            index=dataframe.index,
            dtype=float,
            name="dqn_q_margin",
        )

    q_values = (
        dataframe[
            q_columns
        ]
        .apply(
            pd.to_numeric,
            errors="coerce",
        )
        .to_numpy(
            dtype=float
        )
    )

    margins = []

    for row in q_values:

        if not np.isfinite(
            row
        ).all():

            margins.append(
                np.nan
            )

            continue

        ordered = np.sort(
            row
        )

        margin = float(
            ordered[
                -1
            ]
            -
            ordered[
                -2
            ]
        )

        margins.append(
            margin
        )

    return pd.Series(
        margins,
        index=dataframe.index,
        dtype=float,
        name="dqn_q_margin",
    )


# =============================================================================
# APPLY RL FEEDBACK
# =============================================================================

def apply_rl_feedback(
    mpt_solution: pd.DataFrame,
) -> pd.DataFrame:
    """
    Apply Agent-4 DQN trade feedback to MPT weights.

    Rules
    -----
    SELL:
        force target weight to zero

    BUY:
        preserve MPT weight

    HOLD:
        preserve MPT weight

    After action masking, remaining weights are normalized to sum to one.
    """

    result = (
        mpt_solution
        .copy()
    )

    # =========================================================================
    # ACTION MASK
    # =========================================================================

    result[
        "rl_action_mask"
    ] = np.where(
        result[
            "trade_action"
        ]
        ==
        cfg.ACTION_SELL,

        0.0,

        1.0,
    )

    # =========================================================================
    # RAW RL-ADJUSTED WEIGHT
    # =========================================================================

    result[
        "rl_raw_weight"
    ] = (
        result[
            "mpt_weight"
        ]
        *
        result[
            "rl_action_mask"
        ]
    )

    raw_sum = float(
        result[
            "rl_raw_weight"
        ]
        .sum()
    )

    if raw_sum <= cfg.FLOAT_TOLERANCE:

        raise ValueError(
            "RL feedback removed all portfolio allocation."
        )

    # =========================================================================
    # NORMALIZE
    # =========================================================================

    result[
        "rl_adjusted_weight"
    ] = (
        result[
            "rl_raw_weight"
        ]
        /
        raw_sum
        *
        cfg.WEIGHT_SUM_TARGET
    )

    # Very small numerical values become exact zero.
    result.loc[
        np.abs(
            result[
                "rl_adjusted_weight"
            ]
        )
        <
        1e-12,
        "rl_adjusted_weight",
    ] = 0.0

    # =========================================================================
    # FINAL SAFETY ENFORCEMENT
    # =========================================================================

    sell_mask = (
        result[
            "trade_action"
        ]
        ==
        cfg.ACTION_SELL
    )

    result.loc[
        sell_mask,
        "rl_adjusted_weight",
    ] = (
        cfg.SELL_TARGET_WEIGHT
    )

    # Re-normalize after explicit SELL enforcement.
    eligible_mask = (
        ~sell_mask
    )

    eligible_sum = float(
        result.loc[
            eligible_mask,
            "rl_adjusted_weight",
        ]
        .sum()
    )

    if eligible_sum <= cfg.FLOAT_TOLERANCE:

        raise ValueError(
            "No positive BUY/HOLD allocation remains."
        )

    result.loc[
        eligible_mask,
        "rl_adjusted_weight",
    ] = (
        result.loc[
            eligible_mask,
            "rl_adjusted_weight",
        ]
        /
        eligible_sum
        *
        cfg.WEIGHT_SUM_TARGET
    )

    # =========================================================================
    # PERCENTAGE
    # =========================================================================

    result[
        "rl_adjusted_allocation_percent"
    ] = (
        result[
            "rl_adjusted_weight"
        ]
        *
        100.0
    )

    # =========================================================================
    # CHANGE FROM MPT
    # =========================================================================

    result[
        "rl_weight_change"
    ] = (
        result[
            "rl_adjusted_weight"
        ]
        -
        result[
            "mpt_weight"
        ]
    )

    result[
        "rl_absolute_weight_change"
    ] = np.abs(
        result[
            "rl_weight_change"
        ]
    )

    # =========================================================================
    # RL FEEDBACK LABEL
    # =========================================================================

    result[
        "rl_feedback"
    ] = np.select(
        [
            result[
                "trade_action"
            ]
            ==
            cfg.ACTION_SELL,

            result[
                "trade_action"
            ]
            ==
            cfg.ACTION_BUY,

            result[
                "trade_action"
            ]
            ==
            cfg.ACTION_HOLD,
        ],
        [
            "SELL_ZERO_ALLOCATION",
            "BUY_MPT_ALLOCATION",
            "HOLD_MPT_ALLOCATION",
        ],
        default="UNKNOWN",
    )

    # =========================================================================
    # Q-MARGIN DIAGNOSTIC
    # =========================================================================

    result[
        "dqn_q_margin"
    ] = calculate_q_margin(
        result
    )

    # =========================================================================
    # RANK
    # =========================================================================

    result[
        "rl_allocation_rank"
    ] = (
        result[
            "rl_adjusted_weight"
        ]
        .rank(
            method="dense",
            ascending=False,
        )
        .astype(int)
    )

    # =========================================================================
    # FINAL WEIGHT
    # =========================================================================
    #
    # At this stage rl_adjusted_weight becomes the candidate final weight.
    #
    # rebalancing_environment.py may later model transition from current
    # weights to these target weights.
    # =========================================================================

    result[
        "final_target_weight"
    ] = (
        result[
            "rl_adjusted_weight"
        ]
    )

    result[
        "final_target_allocation_percent"
    ] = (
        result[
            "final_target_weight"
        ]
        *
        100.0
    )

    # =========================================================================
    # SORT
    # =========================================================================

    result = (
        result
        .sort_values(
            [
                "final_target_weight",
                "symbol",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )

    return result


# =============================================================================
# VALIDATE RL FEEDBACK
# =============================================================================

def validate_rl_feedback(
    dataframe: pd.DataFrame,
) -> dict[str, bool]:
    """
    Validate final Agent-4-DQN -> Agent-5-MPT feedback.
    """

    weights = (
        dataframe[
            "rl_adjusted_weight"
        ]
        .to_numpy(
            dtype=float
        )
    )

    mpt_weights = (
        dataframe[
            "mpt_weight"
        ]
        .to_numpy(
            dtype=float
        )
    )

    sell_mask = (
        dataframe[
            "trade_action"
        ]
        ==
        cfg.ACTION_SELL
    )

    eligible_mask = (
        dataframe[
            "trade_action"
        ]
        .isin(
            cfg.MPT_ELIGIBLE_ACTIONS
        )
    )

    checks: dict[str, bool] = {}

    checks[
        "feedback_not_empty"
    ] = (
        not dataframe.empty
    )

    checks[
        "one_row_per_symbol"
    ] = (
        not dataframe[
            "symbol"
        ]
        .duplicated()
        .any()
    )

    checks[
        "actions_valid"
    ] = bool(
        dataframe[
            "trade_action"
        ]
        .isin(
            cfg.VALID_ACTIONS
        )
        .all()
    )

    checks[
        "weights_finite"
    ] = bool(
        np.isfinite(
            weights
        )
        .all()
    )

    checks[
        "weights_nonnegative"
    ] = bool(
        (
            weights
            >=
            (
                cfg.MIN_WEIGHT
                -
                cfg.FLOAT_TOLERANCE
            )
        )
        .all()
    )

    checks[
        "weights_below_max"
    ] = bool(
        (
            weights
            <=
            (
                cfg.MAX_WEIGHT
                +
                cfg.FLOAT_TOLERANCE
            )
        )
        .all()
    )

    checks[
        "weights_sum_to_one"
    ] = bool(
        np.isclose(
            weights.sum(),
            cfg.WEIGHT_SUM_TARGET,
            atol=cfg.WEIGHT_SUM_TOLERANCE,
        )
    )

    # -------------------------------------------------------------------------
    # SELL must always be zero.
    # -------------------------------------------------------------------------

    if sell_mask.any():

        checks[
            "sell_weights_zero"
        ] = bool(
            np.allclose(
                dataframe.loc[
                    sell_mask,
                    "rl_adjusted_weight",
                ]
                .to_numpy(
                    dtype=float
                ),
                cfg.SELL_TARGET_WEIGHT,
                atol=cfg.FLOAT_TOLERANCE,
            )
        )

    else:

        checks[
            "sell_weights_zero"
        ] = True

    # -------------------------------------------------------------------------
    # BUY/HOLD remain allocation eligible.
    # -------------------------------------------------------------------------

    checks[
        "eligible_action_mask_valid"
    ] = bool(
        (
            dataframe.loc[
                eligible_mask,
                "rl_action_mask",
            ]
            ==
            1.0
        )
        .all()
    )

    checks[
        "sell_action_mask_valid"
    ] = bool(
        (
            dataframe.loc[
                sell_mask,
                "rl_action_mask",
            ]
            ==
            0.0
        )
        .all()
    ) if sell_mask.any() else True

    # -------------------------------------------------------------------------
    # Current MPT stage already excludes SELL assets.
    #
    # Therefore RL feedback should usually preserve MPT weights nearly
    # exactly.
    #
    # This check ensures we are not silently inventing BUY/HOLD multipliers.
    # -------------------------------------------------------------------------

    checks[
        "no_arbitrary_buy_hold_modifier"
    ] = bool(
        np.allclose(
            dataframe.loc[
                eligible_mask,
                "rl_adjusted_weight",
            ]
            .to_numpy(
                dtype=float
            ),
            dataframe.loc[
                eligible_mask,
                "mpt_weight",
            ]
            .to_numpy(
                dtype=float
            ),
            atol=cfg.WEIGHT_SUM_TOLERANCE,
            rtol=1e-6,
        )
    )

    checks[
        "mpt_weights_finite"
    ] = bool(
        np.isfinite(
            mpt_weights
        )
        .all()
    )

    checks[
        "final_target_equals_rl_weight"
    ] = bool(
        np.allclose(
            dataframe[
                "final_target_weight"
            ]
            .to_numpy(
                dtype=float
            ),
            weights,
            atol=cfg.FLOAT_TOLERANCE,
        )
    )

    return checks


# =============================================================================
# COMPLETE RL FEEDBACK PIPELINE
# =============================================================================

def run_rl_feedback() -> dict[str, Any]:
    """
    Execute Agent-4 DQN feedback over the Agent-5 MPT portfolio.
    """

    print()
    print(
        "=" * 100
    )

    print(
        "AGENT 5 - RL FEEDBACK"
    )

    print(
        "=" * 100
    )

    print()

    # =========================================================================
    # VERIFY MPT
    # =========================================================================

    mpt_report = (
        load_mpt_report()
    )

    print(
        f"MPT status              : "
        f"{mpt_report.get('status')}"
    )

    print(
        f"MPT optimizer           : "
        f"{mpt_report.get('optimizer')}"
    )

    print(
        f"Target return mode      : "
        f"{mpt_report.get('target_return_mode')}"
    )

    # =========================================================================
    # LOAD MPT SOLUTION
    # =========================================================================

    mpt_solution = (
        load_mpt_solution()
    )

    print(
        f"Portfolio stocks        : "
        f"{len(mpt_solution)}"
    )

    action_counts = (
        mpt_solution[
            "trade_action"
        ]
        .value_counts()
        .to_dict()
    )

    print(
        f"BUY actions             : "
        f"{action_counts.get('BUY', 0)}"
    )

    print(
        f"HOLD actions            : "
        f"{action_counts.get('HOLD', 0)}"
    )

    print(
        f"SELL actions            : "
        f"{action_counts.get('SELL', 0)}"
    )

    # =========================================================================
    # APPLY FEEDBACK
    # =========================================================================

    result = apply_rl_feedback(
        mpt_solution
    )

    # =========================================================================
    # DISPLAY ALLOCATION
    # =========================================================================

    print()
    print(
        "=" * 100
    )

    print(
        "RL-ADJUSTED PORTFOLIO"
    )

    print(
        "=" * 100
    )

    print()

    display_columns = [
        "symbol",
        "trade_action",
        "mpt_weight",
        "rl_adjusted_weight",
        "rl_feedback",
    ]

    available_display_columns = [
        column
        for column in display_columns
        if column in result.columns
    ]

    display = (
        result[
            available_display_columns
        ]
        .copy()
    )

    display[
        "mpt_weight"
    ] = (
        display[
            "mpt_weight"
        ]
        *
        100.0
    )

    display[
        "rl_adjusted_weight"
    ] = (
        display[
            "rl_adjusted_weight"
        ]
        *
        100.0
    )

    display = display.rename(
        columns={
            "mpt_weight":
                "mpt_weight_%",
            "rl_adjusted_weight":
                "rl_weight_%",
        }
    )

    print(
        display.to_string(
            index=False
        )
    )

    # =========================================================================
    # VALIDATE
    # =========================================================================

    checks = validate_rl_feedback(
        result
    )

    overall_pass = all(
        checks.values()
    )

    print()
    print(
        "=" * 100
    )

    print(
        "RL FEEDBACK VALIDATION"
    )

    print(
        "=" * 100
    )

    print()

    for name, passed in checks.items():

        print(
            f"{name:<60}: "
            f"{passed}"
        )

    print()

    print(
        "VALIDATION RESULT: "
        f"{'PASS' if overall_pass else 'FAIL'}"
    )

    if not overall_pass:

        failed = [
            name
            for name, passed
            in checks.items()
            if not passed
        ]

        raise ValueError(
            "RL feedback validation failed:\n"
            +
            "\n".join(
                f"  - {name}"
                for name
                in failed
            )
        )

    # =========================================================================
    # SAVE
    # =========================================================================

    cfg.RL_ADJUSTED_WEIGHTS_CSV.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    result.to_csv(
        cfg.RL_ADJUSTED_WEIGHTS_CSV,
        index=False,
    )

    # =========================================================================
    # SUMMARY STATISTICS
    # =========================================================================

    mpt_weight_sum = float(
        result[
            "mpt_weight"
        ]
        .sum()
    )

    rl_weight_sum = float(
        result[
            "rl_adjusted_weight"
        ]
        .sum()
    )

    total_absolute_adjustment = float(
        result[
            "rl_absolute_weight_change"
        ]
        .sum()
    )

    sell_symbols = (
        result.loc[
            result[
                "trade_action"
            ]
            ==
            cfg.ACTION_SELL,
            "symbol",
        ]
        .tolist()
    )

    buy_symbols = (
        result.loc[
            result[
                "trade_action"
            ]
            ==
            cfg.ACTION_BUY,
            "symbol",
        ]
        .tolist()
    )

    hold_symbols = (
        result.loc[
            result[
                "trade_action"
            ]
            ==
            cfg.ACTION_HOLD,
            "symbol",
        ]
        .tolist()
    )

    # =========================================================================
    # REPORT
    # =========================================================================

    report = {
        "status":
            "COMPLETE",

        "stage":
            "Agent-4 DQN feedback applied to Agent-5 MPT solution",

        "rebalance_date":
            cfg.FINAL_REBALANCE_DATE,

        "stocks":
            int(
                len(
                    result
                )
            ),

        "actions": {
            "BUY":
                int(
                    action_counts.get(
                        "BUY",
                        0,
                    )
                ),

            "HOLD":
                int(
                    action_counts.get(
                        "HOLD",
                        0,
                    )
                ),

            "SELL":
                int(
                    action_counts.get(
                        "SELL",
                        0,
                    )
                ),
        },

        "buy_symbols":
            buy_symbols,

        "hold_symbols":
            hold_symbols,

        "sell_symbols":
            sell_symbols,

        "weight_summary": {
            "mpt_weight_sum":
                mpt_weight_sum,

            "rl_adjusted_weight_sum":
                rl_weight_sum,

            "total_absolute_adjustment":
                total_absolute_adjustment,
        },

        "final_weights": {
            str(
                row[
                    "symbol"
                ]
            ):
                float(
                    row[
                        "rl_adjusted_weight"
                    ]
                )

            for _, row
            in result.iterrows()
        },

        "validation": {
            name:
                bool(
                    passed
                )

            for name, passed
            in checks.items()
        },

        "input":
            str(
                cfg.MPT_SOLUTION_CSV
            ),

        "output":
            str(
                cfg.RL_ADJUSTED_WEIGHTS_CSV
            ),

        "methodology_note":
            (
                "Agent 4 is the learned DQN reinforcement-learning "
                "component. Agent 5 uses those DQN actions as feedback "
                "for portfolio rebalancing. SELL actions enforce zero "
                "allocation. BUY and HOLD actions preserve the allocation "
                "selected by Markowitz MPT. No arbitrary BUY or HOLD "
                "weight multiplier is introduced because the reference "
                "paper does not report such parameters."
            ),
    }

    cfg.REPORT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    with open(
        cfg.RL_FEEDBACK_SUMMARY,
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            report,
            file,
            indent=4,
        )

    # =========================================================================
    # FILES
    # =========================================================================

    print()
    print(
        "=" * 100
    )

    print(
        "GENERATED FILES"
    )

    print(
        "=" * 100
    )

    print()

    print(
        f"RL-adjusted weights     : "
        f"{cfg.RL_ADJUSTED_WEIGHTS_CSV}"
    )

    print(
        f"RL feedback summary     : "
        f"{cfg.RL_FEEDBACK_SUMMARY}"
    )

    # =========================================================================
    # FINAL STATUS
    # =========================================================================

    print()
    print(
        "=" * 100
    )

    print(
        "RL FEEDBACK STATUS"
    )

    print(
        "=" * 100
    )

    print()

    print(
        "MPT solution loading    : COMPLETE"
    )

    print(
        "DQN action transfer     : COMPLETE"
    )

    print(
        "SELL zero allocation    : COMPLETE"
    )

    print(
        "BUY allocation transfer : COMPLETE"
    )

    print(
        "HOLD allocation transfer: COMPLETE"
    )

    print(
        "Weight normalization    : COMPLETE"
    )

    print(
        "Feedback validation     : COMPLETE"
    )

    print()

    print(
        "RL FEEDBACK STATUS: COMPLETE"
    )

    return {
        "mpt_solution":
            mpt_solution,

        "rl_adjusted":
            result,

        "checks":
            checks,

        "report":
            report,
    }


# =============================================================================
# DIRECT EXECUTION
# =============================================================================

if __name__ == "__main__":

    run_rl_feedback()