"""
Tests for Agent 5 - Portfolio Rebalancing Data Loader
===============================================================================

These tests validate the outputs generated by:

    portfolio_rebalancing_agent/src/data_loader.py

The tests do NOT regenerate the complete Agent-5 pipeline.

They verify:

1. Required processed files exist
2. Return matrix is valid
3. Expected number of assets is present
4. Minimum historical observations are available
5. Covariance matrix is square and symmetric
6. Covariance matrix is positive semidefinite
7. Correlation matrix is valid
8. Rebalancing input contains required fields
9. Agent-4 SELL stocks are excluded from MPT
10. BUY/HOLD stocks remain MPT eligible
11. No future data enters Agent 5
12. Agent-3 and Agent-4 symbol transfer is preserved
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
import pytest


# =============================================================================
# PATH SETUP
# =============================================================================

TEST_DIR = (
    Path(__file__)
    .resolve()
    .parent
)

AGENT_ROOT = (
    TEST_DIR
    .parent
)

PROJECT_ROOT = (
    AGENT_ROOT
    .parent
)

if str(AGENT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(AGENT_ROOT),
    )

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(
        0,
        str(PROJECT_ROOT),
    )


from config import config as cfg


# =============================================================================
# HELPERS
# =============================================================================

def load_returns() -> pd.DataFrame:
    """
    Load Agent-5 return matrix.
    """

    if cfg.RETURNS_MATRIX_PARQUET.exists():

        dataframe = pd.read_parquet(
            cfg.RETURNS_MATRIX_PARQUET
        )

    elif cfg.RETURNS_MATRIX_CSV.exists():

        dataframe = pd.read_csv(
            cfg.RETURNS_MATRIX_CSV
        )

    else:

        raise FileNotFoundError(
            "Agent-5 return matrix not found."
        )

    assert "date" in dataframe.columns

    dataframe[
        "date"
    ] = pd.to_datetime(
        dataframe[
            "date"
        ],
        errors="coerce",
    )

    assert not dataframe[
        "date"
    ].isna().any()

    return (
        dataframe
        .set_index("date")
        .sort_index()
    )


def load_rebalancing_input() -> pd.DataFrame:
    """
    Load Agent-5 rebalancing input.
    """

    if cfg.REBALANCING_INPUT_PARQUET.exists():

        dataframe = pd.read_parquet(
            cfg.REBALANCING_INPUT_PARQUET
        )

    elif cfg.REBALANCING_INPUT_CSV.exists():

        dataframe = pd.read_csv(
            cfg.REBALANCING_INPUT_CSV
        )

    else:

        raise FileNotFoundError(
            "Agent-5 rebalancing input not found."
        )

    return dataframe


def normalize_bool(
    series: pd.Series,
) -> pd.Series:
    """
    Normalize boolean representation.
    """

    if series.dtype == bool:

        return series

    return (
        series
        .astype(str)
        .str.strip()
        .str.lower()
        .isin(
            [
                "true",
                "1",
                "yes",
            ]
        )
    )


# =============================================================================
# FILE TESTS
# =============================================================================

def test_required_agent5_processed_files_exist():
    """
    All core data-loader outputs must exist.
    """

    assert (
        cfg.RETURNS_MATRIX_PARQUET.exists()
        or
        cfg.RETURNS_MATRIX_CSV.exists()
    )

    assert cfg.COVARIANCE_MATRIX_CSV.exists()

    assert cfg.CORRELATION_MATRIX_CSV.exists()

    assert (
        cfg.ASSET_STATISTICS_PARQUET.exists()
        or
        cfg.ASSET_STATISTICS_CSV.exists()
    )

    assert (
        cfg.REBALANCING_INPUT_PARQUET.exists()
        or
        cfg.REBALANCING_INPUT_CSV.exists()
    )

    assert cfg.DATA_LOADER_SUMMARY.exists()


# =============================================================================
# RETURN MATRIX TESTS
# =============================================================================

def test_returns_matrix_not_empty():
    """
    Historical return matrix must contain data.
    """

    returns = load_returns()

    assert not returns.empty


def test_returns_matrix_has_expected_stock_count():
    """
    Agent-5 return matrix should contain the 10 stocks transferred from
    Agent 4.
    """

    returns = load_returns()

    assert returns.shape[
        1
    ] == 10


def test_returns_matrix_minimum_history():
    """
    Markowitz covariance estimation requires sufficient observations.
    """

    returns = load_returns()

    assert len(
        returns
    ) >= cfg.MIN_REQUIRED_RETURN_OBSERVATIONS


def test_returns_matrix_lookback_limit():
    """
    The selected estimation window must not exceed configured lookback.
    """

    returns = load_returns()

    assert len(
        returns
    ) <= cfg.ESTIMATION_LOOKBACK_DAYS


def test_returns_matrix_values_are_finite():
    """
    Returns must not contain NaN or infinity.
    """

    returns = load_returns()

    values = (
        returns
        .apply(
            pd.to_numeric,
            errors="coerce",
        )
        .to_numpy(
            dtype=float
        )
    )

    assert np.isfinite(
        values
    ).all()


def test_returns_do_not_use_future_data():
    """
    No historical observation may occur after final rebalance date.
    """

    returns = load_returns()

    assert (
        returns.index
        <=
        pd.Timestamp(
            cfg.FINAL_REBALANCE_DATE
        )
    ).all()


# =============================================================================
# COVARIANCE TESTS
# =============================================================================

def test_covariance_matrix_is_square():
    """
    MPT covariance matrix must be square.
    """

    covariance = pd.read_csv(
        cfg.COVARIANCE_MATRIX_CSV,
        index_col=0,
    )

    assert covariance.shape[
        0
    ] == covariance.shape[
        1
    ]


def test_covariance_matrix_is_symmetric():
    """
    Covariance matrix must satisfy:

        Σ = Σ.T
    """

    covariance = pd.read_csv(
        cfg.COVARIANCE_MATRIX_CSV,
        index_col=0,
    )

    values = covariance.to_numpy(
        dtype=float
    )

    assert np.allclose(
        values,
        values.T,
        atol=1e-10,
    )


def test_covariance_matrix_is_finite():
    """
    Covariance matrix must contain finite values.
    """

    covariance = pd.read_csv(
        cfg.COVARIANCE_MATRIX_CSV,
        index_col=0,
    )

    values = covariance.to_numpy(
        dtype=float
    )

    assert np.isfinite(
        values
    ).all()


def test_covariance_matrix_positive_semidefinite():
    """
    Valid covariance matrices must be positive semidefinite.
    """

    covariance = pd.read_csv(
        cfg.COVARIANCE_MATRIX_CSV,
        index_col=0,
    )

    values = covariance.to_numpy(
        dtype=float
    )

    eigenvalues = np.linalg.eigvalsh(
        values
    )

    assert np.min(
        eigenvalues
    ) >= -1e-8


# =============================================================================
# CORRELATION TESTS
# =============================================================================

def test_correlation_matrix_is_square():
    """
    Correlation matrix must be square.
    """

    correlation = pd.read_csv(
        cfg.CORRELATION_MATRIX_CSV,
        index_col=0,
    )

    assert correlation.shape[
        0
    ] == correlation.shape[
        1
    ]


def test_correlation_matrix_is_symmetric():
    """
    Correlation matrix must be symmetric.
    """

    correlation = pd.read_csv(
        cfg.CORRELATION_MATRIX_CSV,
        index_col=0,
    )

    values = correlation.to_numpy(
        dtype=float
    )

    assert np.allclose(
        values,
        values.T,
        atol=1e-10,
    )


def test_correlation_values_are_valid():
    """
    Correlations must lie approximately between -1 and +1.
    """

    correlation = pd.read_csv(
        cfg.CORRELATION_MATRIX_CSV,
        index_col=0,
    )

    values = correlation.to_numpy(
        dtype=float
    )

    assert np.isfinite(
        values
    ).all()

    assert np.min(
        values
    ) >= -1.000001

    assert np.max(
        values
    ) <= 1.000001


# =============================================================================
# REBALANCING INPUT TESTS
# =============================================================================

def test_rebalancing_input_required_columns():
    """
    Core Agent-5 fields must be available.
    """

    dataframe = (
        load_rebalancing_input()
    )

    required_columns = {
        "symbol",
        "trade_action",
        "eligible_for_mpt",
        "mean_daily_return",
        "annualized_expected_return",
        "annualized_volatility",
    }

    assert required_columns.issubset(
        dataframe.columns
    )


def test_rebalancing_input_has_ten_unique_symbols():
    """
    Agent 5 should receive all 10 Agent-4 symbols.
    """

    dataframe = (
        load_rebalancing_input()
    )

    assert len(
        dataframe
    ) == 10

    assert dataframe[
        "symbol"
    ].nunique() == 10


def test_agent4_action_distribution_preserved():
    """
    Current validated Agent-4 output contains:

        BUY  = 1
        HOLD = 7
        SELL = 2
    """

    dataframe = (
        load_rebalancing_input()
    )

    actions = (
        dataframe[
            "trade_action"
        ]
        .astype(str)
        .str.upper()
        .value_counts()
        .to_dict()
    )

    assert actions.get(
        "BUY",
        0,
    ) == 1

    assert actions.get(
        "HOLD",
        0,
    ) == 7

    assert actions.get(
        "SELL",
        0,
    ) == 2


# =============================================================================
# MPT ELIGIBILITY TESTS
# =============================================================================

def test_sell_stocks_are_not_mpt_eligible():
    """
    Agent-4 SELL stocks must be excluded from positive MPT allocation.
    """

    dataframe = (
        load_rebalancing_input()
    )

    eligible = normalize_bool(
        dataframe[
            "eligible_for_mpt"
        ]
    )

    sell_mask = (
        dataframe[
            "trade_action"
        ]
        .astype(str)
        .str.upper()
        .eq(
            cfg.ACTION_SELL
        )
    )

    assert (
        ~eligible[
            sell_mask
        ]
    ).all()


def test_buy_hold_stocks_are_mpt_eligible():
    """
    Agent-4 BUY and HOLD stocks remain eligible for MPT.
    """

    dataframe = (
        load_rebalancing_input()
    )

    eligible = normalize_bool(
        dataframe[
            "eligible_for_mpt"
        ]
    )

    buy_hold_mask = (
        dataframe[
            "trade_action"
        ]
        .astype(str)
        .str.upper()
        .isin(
            cfg.MPT_ELIGIBLE_ACTIONS
        )
    )

    assert eligible[
        buy_hold_mask
    ].all()


def test_mpt_eligible_stock_count():
    """
    Current Agent-4 output has eight MPT-eligible BUY/HOLD stocks.
    """

    dataframe = (
        load_rebalancing_input()
    )

    eligible = normalize_bool(
        dataframe[
            "eligible_for_mpt"
        ]
    )

    assert int(
        eligible.sum()
    ) == 8


def test_mpt_covariance_symbols_equal_eligible_symbols():
    """
    Covariance matrix must contain exactly the MPT-eligible assets.
    """

    dataframe = (
        load_rebalancing_input()
    )

    eligible = normalize_bool(
        dataframe[
            "eligible_for_mpt"
        ]
    )

    eligible_symbols = set(
        dataframe.loc[
            eligible,
            "symbol",
        ]
        .astype(str)
    )

    covariance = pd.read_csv(
        cfg.COVARIANCE_MATRIX_CSV,
        index_col=0,
    )

    covariance_symbols = set(
        covariance.columns.astype(
            str
        )
    )

    assert covariance_symbols == eligible_symbols


# =============================================================================
# AGENT-3 / AGENT-4 TRANSFER TEST
# =============================================================================

def test_agent3_and_agent4_symbols_match():
    """
    Agent-3 risk output and Agent-4 trade output must refer to the same
    final stock universe entering Agent 5.
    """

    if cfg.AGENT3_RISK_PARQUET.exists():

        agent3 = pd.read_parquet(
            cfg.AGENT3_RISK_PARQUET
        )

    else:

        agent3 = pd.read_csv(
            cfg.AGENT3_RISK_CSV
        )

    if cfg.AGENT4_TRADE_DECISIONS_PARQUET.exists():

        agent4 = pd.read_parquet(
            cfg.AGENT4_TRADE_DECISIONS_PARQUET
        )

    else:

        agent4 = pd.read_csv(
            cfg.AGENT4_TRADE_DECISIONS_CSV
        )

    agent3_symbols = set(
        agent3[
            "symbol"
        ]
        .astype(str)
        .str.strip()
    )

    agent4_symbols = set(
        agent4[
            "symbol"
        ]
        .astype(str)
        .str.strip()
    )

    assert agent3_symbols == agent4_symbols