"""
Agent 3 - Risk Management Agent
Configuration
===============================================================

Base-paper core components
--------------------------
1. Historical volatility
2. Value at Risk (VaR)
3. Sharpe Ratio
4. Risk-adjusted portfolio allocation

Paper equations
---------------
Portfolio VaR:

    VaR = z * sqrt(w.T @ Sigma @ w)

where:

    z       = confidence-level z-score
    w       = portfolio weight vector
    Sigma   = return covariance matrix


Sharpe Ratio:

    SR = (Rp - Rf) / sigma_p

where:

    Rp      = portfolio return
    Rf      = risk-free return
    sigma_p = portfolio volatility


IMPORTANT
---------
The paper does not clearly provide all numerical parameters such as:

- exact historical lookback window
- VaR confidence level
- exact risk-free rate
- exact portfolio weighting procedure

Those parameters below are therefore explicitly marked as
implementation choices.
"""

from pathlib import Path


# ============================================================
# BASIC AGENT INFORMATION
# ============================================================

AGENT_NUMBER = 3

AGENT_NAME = "Risk Management Agent"


# ============================================================
# PROJECT PATHS
# ============================================================

CONFIG_FILE = Path(__file__).resolve()

RISK_AGENT_ROOT = CONFIG_FILE.parents[1]

PROJECT_ROOT = RISK_AGENT_ROOT.parent


# ============================================================
# UPSTREAM AGENTS
# ============================================================

STOCK_SELECTION_AGENT_ROOT = (
    PROJECT_ROOT
    / "stock_selection_agent"
)

TREND_PREDICTION_AGENT_ROOT = (
    PROJECT_ROOT
    / "trend_prediction_agent"
)


# ============================================================
# AGENT 2 FINAL OUTPUT
# ============================================================

AGENT2_PREDICTIONS_PARQUET = (
    TREND_PREDICTION_AGENT_ROOT
    / "outputs"
    / "trend_predictions.parquet"
)

AGENT2_PREDICTIONS_CSV = (
    TREND_PREDICTION_AGENT_ROOT
    / "outputs"
    / "trend_predictions.csv"
)


# ============================================================
# HISTORICAL MARKET DATA
# ============================================================

# Reuse the already-cleaned historical OHLCV dataset
# generated by Agent 1.

HISTORICAL_DATA_FILE = (
    STOCK_SELECTION_AGENT_ROOT
    / "data"
    / "processed"
    / "nifty500_daily.parquet"
)


# ============================================================
# AGENT 3 DIRECTORIES
# ============================================================

DATA_DIR = (
    RISK_AGENT_ROOT
    / "data"
)

INPUT_DIR = (
    DATA_DIR
    / "inputs"
)

PROCESSED_DIR = (
    DATA_DIR
    / "processed"
)

OUTPUT_DIR = (
    RISK_AGENT_ROOT
    / "outputs"
)

REPORT_DIR = (
    RISK_AGENT_ROOT
    / "reports"
)


for directory in [

    INPUT_DIR,
    PROCESSED_DIR,
    OUTPUT_DIR,
    REPORT_DIR,

]:

    directory.mkdir(
        parents=True,
        exist_ok=True,
    )


# ============================================================
# MARKET CONVENTIONS
# ============================================================

TRADING_DAYS_PER_YEAR = 252


# ============================================================
# RETURN SETTINGS
# ============================================================

# We use simple daily returns:
#
#     Rt = Close_t / Close_(t-1) - 1

RETURN_COLUMN = "daily_return"


# ============================================================
# HISTORICAL LOOKBACK
# ============================================================

# IMPLEMENTATION CHOICE
#
# The paper says historical volatility is analysed but does not
# clearly specify the exact lookback period.
#
# 252 trading days approximates one trading year.

RISK_LOOKBACK_DAYS = 252


# Minimum acceptable history.

MIN_HISTORY_DAYS = 60


# ============================================================
# HISTORICAL VOLATILITY
# ============================================================

# Additional reporting windows.
#
# These are implementation choices.

VOLATILITY_WINDOWS = [

    20,

    60,

    252,

]


ANNUALIZE_VOLATILITY = True


# ============================================================
# VALUE AT RISK
# ============================================================

# Base-paper formula:
#
# VaR = z * sqrt(w.T @ covariance @ w)
#
# We use parametric variance-covariance VaR because this matches
# the mathematical structure shown in the paper.


VAR_CONFIDENCE_LEVEL = 0.95


# 95% one-tailed normal z-score.
#
# Implementation choice because confidence level is not clearly
# specified by the paper.

VAR_Z_SCORE = 1.6448536269514722


# Daily VaR is calculated first.
#
# This also corresponds naturally with the paper's discussion
# of daily VaR during evaluation.

VAR_HORIZON_DAYS = 1


# ============================================================
# SHARPE RATIO
# ============================================================

# Annual risk-free rate.
#
# IMPLEMENTATION CHOICE.
#
# Zero is used initially for reproducibility.
#
# This can later be replaced by an RBI/T-bill rate if desired.

ANNUAL_RISK_FREE_RATE = 0.0


# ============================================================
# INITIAL PORTFOLIO WEIGHTING
# ============================================================

# VaR requires portfolio weights.
#
# At this stage Agent 5 has not yet performed final portfolio
# optimization.
#
# Therefore Agent 3 must begin with a provisional allocation.
#
# We use equal weight as the neutral baseline:
#
#     wi = 1 / N
#
# This is NOT claimed as a paper-specified weighting rule.

INITIAL_WEIGHT_METHOD = "equal"


# ============================================================
# OPTIONAL RISK-ADJUSTED WEIGHTING
# ============================================================

# Agent 3 will later calculate a risk-adjusted allocation using
# trend signal + financial risk.
#
# These weights are implementation choices and will be handled
# inside risk_scorer.py.

ENABLE_RISK_ADJUSTED_WEIGHTS = True


# ============================================================
# AGENT 2 COLUMNS
# ============================================================

REQUIRED_AGENT2_COLUMNS = [

    "symbol",

    "prediction_date",

    "top30_probability",

    "ensemble_std",

    "trend_class",

    "agent2_rank",

]


# ============================================================
# MARKET DATA COLUMNS
# ============================================================

REQUIRED_MARKET_COLUMNS = [

    "symbol",

    "date",

    "open",

    "high",

    "low",

    "close",

    "volume",

]


# ============================================================
# PROCESSED FILES
# ============================================================

RISK_INPUT_FILE = (
    PROCESSED_DIR
    / "risk_input.parquet"
)


RETURN_MATRIX_FILE = (
    PROCESSED_DIR
    / "return_matrix.parquet"
)


COVARIANCE_MATRIX_FILE = (
    PROCESSED_DIR
    / "covariance_matrix.csv"
)


# ============================================================
# FINAL OUTPUT FILES
# ============================================================

RISK_ASSESSMENT_CSV = (
    OUTPUT_DIR
    / "risk_assessment.csv"
)


RISK_ASSESSMENT_PARQUET = (
    OUTPUT_DIR
    / "risk_assessment.parquet"
)


PORTFOLIO_RISK_JSON = (
    OUTPUT_DIR
    / "portfolio_risk.json"
)


RISK_SUMMARY_JSON = (
    REPORT_DIR
    / "risk_summary.json"
)


# ============================================================
# PAPER-ALIGNED COMPONENTS
# ============================================================

PAPER_CORE_COMPONENTS = [

    "Historical Volatility",

    "Value at Risk",

    "Sharpe Ratio",

    "Risk-adjusted portfolio allocation",

]


# ============================================================
# IMPLEMENTATION CHOICES
# ============================================================

IMPLEMENTATION_CHOICES = {

    "risk_lookback_days":
        RISK_LOOKBACK_DAYS,

    "volatility_windows":
        VOLATILITY_WINDOWS,

    "var_confidence":
        VAR_CONFIDENCE_LEVEL,

    "var_z_score":
        VAR_Z_SCORE,

    "risk_free_rate":
        ANNUAL_RISK_FREE_RATE,

    "initial_weights":
        INITIAL_WEIGHT_METHOD,

}


# ============================================================
# AGENT 3 RISK SCORING
# ============================================================

# The paper does not provide an exact formula for converting
# volatility, VaR and Sharpe ratio into one stock-level score.
#
# We therefore use transparent percentile/rank normalization.
#
# Paper-core risk score:
#
#     1/3 low-volatility score
#   + 1/3 low-VaR score
#   + 1/3 high-Sharpe score
#
# Final Agent-3 score then combines:
#
#     Agent-2 trend signal
#     Paper-core risk score
#     Drawdown diagnostic
#
# These weights are IMPLEMENTATION CHOICES.

TREND_SCORE_WEIGHT = 0.50

CORE_RISK_SCORE_WEIGHT = 0.40

DRAWDOWN_SCORE_WEIGHT = 0.10


# ============================================================
# RISK LEVELS
# ============================================================

# Risk levels are determined cross-sectionally from the
# paper-core risk score.
#
# Higher score = better risk profile.

LOW_RISK_THRESHOLD = 2.0 / 3.0

HIGH_RISK_THRESHOLD = 1.0 / 3.0


# ============================================================
# RISK-ADJUSTED ALLOCATION
# ============================================================

# Agent 3 produces provisional risk-adjusted weights.
#
# These are NOT the final portfolio weights.
#
# Agent 5 will later perform final portfolio optimization.

MIN_PROVISIONAL_WEIGHT = 0.0

MAX_PROVISIONAL_WEIGHT = 0.25